name: backend_client
description: Starting point for a Serverpod client.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod_client: 3.1.1
  serverpod_flutter: ^3.1.1
  shared_preferences: ^2.1.1
